<?php
/**
 * Fizz is a lightweight ORM
 *
 * @author Skylar Kelty <skylarkelty@gmail.com>
 */

namespace SkylarK\Fizz;

/**
 * The core of Fizz Introspector
 */
class Introspector
{
	/** Our PDO instance */
	private $_introspector;

	/**
	 * Initialize a Fizz Introspector object.
	 * Only supports MySQL for now..
	 */
	public function __construct() {
		$this->_introspector = new Util\Introspect();
	}


	/**
	 * Saves Fizz Models to a directory
	 * 
	 * @param string $directory The directory to write the PHP model's too
	 * @param string $namespace The namespace for each model
	 */
	public function saveModels($directory, $namespace = '') {
		if (!is_writable($directory)) {
			echo "Cannot write to directory!\n";
			return;
		}

		echo "Running Introspector...\n";

		$tables = $this->_introspector->getTables();

		if (empty($tables)) {
			die("No tables found.\n");
		}

		$count = count($tables);
		echo "Found $count tables...\n";

		foreach ($tables as $table) {
			echo "Processing $table...\n";

			$meta = $this->_introspector->getMeta($table);

			// Support PSR-0 autoloading
			$tClass = str_replace("_", " ", $table);
			$tClass = ucwords($tClass);
			$tClass = str_replace(" ", "", $tClass);

			$file = "<?php\n";
			$file .= "/**\n";
			$file .= " * Automatically generated by Fizz-Introspect\n";
			$file .= " * \n";
			$file .= " * @version " . strftime("%H:%M %d-%m-%Y") . "\n";
			$file .= " * @author Fizz-Introspect\n";
			$file .= " */\n";
			$file .= "\n";
			if (!empty($namespace)) {
				$file .= "namespace $namespace;\n";
			}
			$file .= "\n";
			$file .= "/**\n";
			$file .= " * Fizz Model $tClass for table $table\n";
			$file .= " */\n";
			$file .= "class $tClass extends \SkylarK\Fizz\Fizz\n";
			$file .= "{\n";
			
			// Print vars
			foreach ($meta as $column) {
				$file .= "\tpublic \${$column['name']};\n";
			}

			// Override this method for slightly improved speed
			$file .= "\n";
			$file .= "\t/**\n";
			$file .= "\t * Returns the table name\n";
			$file .= "\t */\n";
			$file .= "\tpublic static function tablename() {\n";
			$file .= "\t\treturn '$table';\n";
			$file .= "\t}\n";

			$file .= "}\n";

			$filename =  "$directory/$tClass.php";

			$f = fopen($filename, "w+");
			if ($f) {
				fwrite($f, $file);
				fclose($f);
			}
		}
	}


	/**
	 * Prints Fizz Models
	 */
	public function printModels() {
		echo "Running Introspector...\n";

		$tables = $this->_introspector->getTables();

		if (empty($tables)) {
			die("No tables found.\n");
		}

		foreach ($tables as $table) {
			$meta = $this->_introspector->getMeta($table);

			echo "class $table extends SkylarK\Fizz\Fizz\n";
			echo "{\n";
			foreach ($meta as $column) {
				echo "\tpublic \${$column['name']};\n";
			}
			echo "}\n";
		}
	}
}
